const seed=[{id:1,text:"Confío en mí y en todo lo que soy capaz de lograr.",category:"Motivación"},{id:2,text:"Cuando me perdono, me libero.",category:"Amor propio"},{id:3,text:"Estoy en constante crecimiento.",category:"Motivación"},{id:4,text:"Atraigo cosas buenas a mi vida.",category:"Gratitud"},{id:5,text:"Soy suficiente, tal como soy.",category:"Amor propio"},{id:6,text:"Cada día es una nueva oportunidad.",category:"Éxito"},{id:7,text:"Respiro, suelto y vuelvo al presente.",category:"Tranquilidad"},{id:8,text:"Mi disciplina construye la vida que deseo.",category:"Disciplina"}];
const cats=[["Todas","✦"],["Motivación","△"],["Amor propio","♡"],["Éxito","↗"],["Tranquilidad","☘"],["Gratitud","☀"],["Disciplina","◇"],["Mis frases","＋"]];
let quotes=JSON.parse(localStorage.getItem("affirmations")||"null")||seed;let favorites=JSON.parse(localStorage.getItem("favorites")||"[]");let category="Todas",index=0;const $=id=>document.getElementById(id);const filtered=()=>quotes.filter(q=>category==="Todas"||q.category===category);
function save(){localStorage.setItem("affirmations",JSON.stringify(quotes));localStorage.setItem("favorites",JSON.stringify(favorites))}
function renderQuote(){const a=filtered();if(!a.length){category="Todas";return renderQuote()}index=(index+a.length)%a.length;const q=a[index];$("quoteText").textContent=q.text;$("counter").textContent=`${index+1}/${a.length}`;$("categoryLabel").textContent=category;$("favoriteBtn").firstChild.textContent=favorites.includes(q.id)?"♥":"♡";$("quoteImage").style.display=q.image?"block":"none";if(q.image)$("quoteImage").src=q.image}
function show(name){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(name).classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("nav-active",b.dataset.view===name));if(name==="favorites")renderFavorites()}
function renderCategories(){$("categoryGrid").innerHTML=cats.map(([c,i])=>`<button class="cat" data-cat="${c}"><span>${i}</span>${c}<small>${c==="Todas"?quotes.length:quotes.filter(q=>q.category===c).length} frases</small></button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{category=b.dataset.cat;index=0;renderQuote();show("home")});$("newCategory").innerHTML=cats.filter(x=>!["Todas","Mis frases"].includes(x[0])).map(x=>`<option>${x[0]}</option>`).join("")+`<option>Mis frases</option>`}
function renderFavorites(){const list=quotes.filter(q=>favorites.includes(q.id));$("favoriteList").innerHTML=list.length?list.map(q=>`<div class="fav"><span>${q.text}<small style="display:block;color:#888">${q.category}</small></span><button data-remove="${q.id}">♥</button></div>`).join(""):"<p>Aún no tienes afirmaciones favoritas.</p>";document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{favorites=favorites.filter(x=>x!=b.dataset.remove);save();renderFavorites();renderQuote()})}
$("nextBtn").onclick=()=>{index++;renderQuote()};$("favoriteBtn").onclick=()=>{const q=filtered()[index];favorites=favorites.includes(q.id)?favorites.filter(x=>x!==q.id):[...favorites,q.id];save();renderQuote()};$("shareBtn").onclick=async()=>{const text=filtered()[index].text;if(navigator.share)navigator.share({title:"Afirmación",text});else{await navigator.clipboard.writeText(text);alert("Frase copiada.")}};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));$("categoriesBtn").onclick=()=>show("categories");$("settingsBtn").onclick=()=>show("settings");
let imageData="";$("newImage").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{imageData=r.result;$("imagePreview").src=imageData;$("imagePreview").style.display="block"};r.readAsDataURL(f)};$("saveBtn").onclick=()=>{const text=$("newText").value.trim();if(!text)return alert("Escribe una afirmación.");quotes.push({id:Date.now(),text,category:$("newCategory").value,image:imageData});save();$("newText").value="";$("newImage").value="";$("imagePreview").style.display="none";imageData="";renderCategories();category="Mis frases";index=filtered().length-1;renderQuote();show("home")};
const gradients={sunset:"linear-gradient(160deg,#ffcfc8,#a8b8dc)",lavender:"linear-gradient(160deg,#ead6ff,#b8bde9)",mint:"linear-gradient(160deg,#d9f4e5,#9fc9c3)",night:"linear-gradient(160deg,#26324a,#73546f)"};function personalize(){const bg=gradients[$("backgroundSelect").value],color=$("colorPicker").value,font=$("fontSelect").value;document.querySelector(".quote-card").style.background=bg;$("settingsPreview").style.background=bg;$("quoteText").style.color=color;$("settingsPreview").style.color=color;const family=font==="sans"?"Inter,Arial,sans-serif":font==="hand"?"cursive":"Georgia,serif";$("quoteText").style.fontFamily=family;$("settingsPreview").style.fontFamily=family}["backgroundSelect","fontSelect","colorPicker"].forEach(id=>$(id).oninput=personalize);renderCategories();renderQuote();personalize();