const seed=[{id:1,text:'Confío en mí y en todo lo que soy capaz de lograr.',category:'Motivación',bg:'dawn'},{id:2,text:'No necesito tener todo resuelto para seguir avanzando.',category:'Amor propio',bg:'ocean'},{id:3,text:'Mi constancia transforma mis sueños en resultados.',category:'Éxito',bg:'night'},{id:4,text:'Hoy elijo agradecer lo que ya está floreciendo.',category:'Gratitud',bg:'forest'},{id:5,text:'Soy suficiente incluso mientras sigo creciendo.',category:'Amor propio',bg:'rose'},{id:6,text:'Respiro profundo. Estoy aquí. Estoy a salvo.',category:'Tranquilidad',bg:'ocean'},{id:7,text:'La disciplina de hoy crea la libertad de mañana.',category:'Disciplina',bg:'night'},{id:8,text:'Merezco relaciones que se sientan recíprocas y tranquilas.',category:'Relaciones',bg:'rose'}];
const cats=[['Todas','✦'],['Motivación','↗'],['Amor propio','♡'],['Éxito','◇'],['Tranquilidad','≈'],['Gratitud','☼'],['Disciplina','△'],['Relaciones','∞'],['Mis frases','＋']];
const gradients={dawn:'linear-gradient(145deg,#c58f82,#536b79)',ocean:'linear-gradient(145deg,#668c99,#263d4a)',forest:'linear-gradient(145deg,#708276,#293b35)',night:'linear-gradient(145deg,#4b526d,#171b2a)',rose:'linear-gradient(145deg,#c68d96,#745d70)'};
const $=id=>document.getElementById(id);let quotes=JSON.parse(localStorage.getItem('alma_quotes')||'null')||seed;let favorites=JSON.parse(localStorage.getItem('alma_favs')||'[]');let prefs=JSON.parse(localStorage.getItem('alma_prefs')||'null')||{bg:'dawn',font:'serif',color:'#ffffff'};let category='Todas',index=0,imageData='';
const filtered=()=>category==='Todas'?quotes:category==='Mis frases'?quotes.filter(q=>q.custom):quotes.filter(q=>q.category===category);const save=()=>{localStorage.setItem('alma_quotes',JSON.stringify(quotes));localStorage.setItem('alma_favs',JSON.stringify(favorites));localStorage.setItem('alma_prefs',JSON.stringify(prefs))};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function renderQuote(direction=0){let list=filtered();if(!list.length){category='Todas';list=filtered()}index=(index+list.length)%list.length;const q=list[index];$('quoteText').textContent=q.text;$('quoteCategory').textContent=q.category;$('categoryLabel').textContent=category==='Todas'?'Para ti':category;$('counter').textContent=`${String(index+1).padStart(2,'0')} / ${String(list.length).padStart(2,'0')}`;$('progressBar').style.width=`${((index+1)/list.length)*100}%`;$('favoriteBtn').textContent=favorites.includes(q.id)?'♥':'♡';$('favoriteBtn').classList.toggle('liked',favorites.includes(q.id));$('hero').style.background=q.image?`linear-gradient(#0002,#0003),url(${q.image}) center/cover`:gradients[q.bg||prefs.bg];$('quoteText').style.color=prefs.color;$('quoteText').style.fontFamily=prefs.font==='sans'?'Inter,sans-serif':prefs.font==='soft'?'cursive':'Georgia,serif';if(direction){$('quoteText').animate([{opacity:0,transform:`translateY(${direction*22}px)`},{opacity:1,transform:'translateY(0)'}],{duration:280})}}
function show(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(name).classList.add('active');document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('selected',b.dataset.open===name));if(name==='favorites')renderFavorites()}
function renderCategories(){$('categoryGrid').innerHTML=cats.map(([c,i])=>{const n=c==='Todas'?quotes.length:c==='Mis frases'?quotes.filter(q=>q.custom).length:quotes.filter(q=>q.category===c).length;return `<button class="cat" data-cat="${c}"><em>${i}</em><b>${c}</b><small>${n} afirmaciones</small></button>`}).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;index=0;renderQuote();show('home')});$('newCategory').innerHTML=cats.slice(1,-1).map(([c])=>`<option>${c}</option>`).join('')}
function renderFavorites(){const list=quotes.filter(q=>favorites.includes(q.id));$('favoriteList').innerHTML=list.length?list.map(q=>`<article class="fav"><div class="fav-text"><strong>${q.text}</strong><small>${q.category}</small></div><button data-remove="${q.id}">♥</button></article>`).join(''):'<div class="empty">♡<br><br>Aquí aparecerán las afirmaciones que quieras guardar contigo.</div>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{favorites=favorites.filter(id=>String(id)!==b.dataset.remove);save();renderFavorites();renderQuote()})}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>show(b.dataset.open));document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show('home'));
$('favoriteBtn').onclick=()=>{const q=filtered()[index];favorites=favorites.includes(q.id)?favorites.filter(id=>id!==q.id):[...favorites,q.id];save();renderQuote();toast(favorites.includes(q.id)?'Guardada en favoritos':'Eliminada de favoritos')};$('shareBtn').onclick=async()=>{const text=filtered()[index].text;try{if(navigator.share)await navigator.share({title:'Una afirmación para ti',text});else{await navigator.clipboard.writeText(text);toast('Frase copiada')}}catch(e){}};
let startY=0,startX=0;$('hero').addEventListener('touchstart',e=>{startY=e.touches[0].clientY;startX=e.touches[0].clientX},{passive:true});$('hero').addEventListener('touchend',e=>{const dy=e.changedTouches[0].clientY-startY,dx=e.changedTouches[0].clientX-startX;if(Math.abs(dy)>55&&Math.abs(dy)>Math.abs(dx)){index+=dy<0?1:-1;renderQuote(dy<0?1:-1)}},{passive:true});$('hero').addEventListener('click',e=>{if(e.target.closest('button'))return;if(e.clientY>$('hero').clientHeight*.35){index++;renderQuote(1)}});
$('newImage').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{imageData=r.result;$('imagePreview').src=imageData;$('imagePreviewBox').style.display='block'};r.readAsDataURL(f)};$('saveBtn').onclick=()=>{const text=$('newText').value.trim();if(!text)return toast('Escribe tu afirmación');const q={id:Date.now(),text,category:$('newCategory').value,image:imageData,custom:true,bg:prefs.bg};quotes.push(q);save();$('newText').value='';$('newImage').value='';$('imagePreviewBox').style.display='none';imageData='';renderCategories();category='Mis frases';index=filtered().length-1;renderQuote();show('home');toast('Tu afirmación está lista')};
function personalize(){prefs={bg:$('backgroundSelect').value,font:$('fontSelect').value,color:$('colorPicker').value};$('settingsPreview').style.background=gradients[prefs.bg];$('settingsPreview').style.color=prefs.color;$('settingsPreview').querySelector('strong').style.fontFamily=prefs.font==='sans'?'Inter,sans-serif':prefs.font==='soft'?'cursive':'Georgia,serif';save();renderQuote()}$('backgroundSelect').value=prefs.bg;$('fontSelect').value=prefs.font;$('colorPicker').value=prefs.color;['backgroundSelect','fontSelect','colorPicker'].forEach(id=>$(id).oninput=personalize);renderCategories();renderQuote();personalize();